name: 'test'
description: 'hello'
outputs:
  VAR1: 
    description: "Random number"
    value: ${{steps.step1.outputs.VAR1}}
runs:
  using: "composite"
  steps:
  - id: step1
    shell: bash
    run: echo "::set-output name=VAR1::Hamel"
  - id: step2
    shell: bash
    run: echo "::set-output name=VAR2::Husain"
  - id: emit_env
    shell: bash
    run: |
      echo ${{steps.step1.outputs.VAR1}}
      echo ${{steps.step1.outputs.VAR2}}
  - id: this-should-not-run
    shell: bash
    run: echo "This should not run"