name: React App Staging

on:
  push:
  pull_request:
    branches: [ $default-branch ]

jobs:
  info:
    name: get information
    runs-on: ubuntu-latest
    outputs:
    - TRANCH_NAME: ${{ steps.step1.outputs.TRANCH_NAME }}

    steps:
    - name: sets branch/tag name
      id: step1
      run: |
            ref="${github_ref////-}"
            echo $ref
            echo "::set-output name=TRANCH_NAME::$ref"
  build:
      name: builds react app
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: 14.x

      steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: clean install dependencies
        run: npm ci
      
      - name: build app
        run: npm run build --if-present
      
      - name: test app
        run: npm test --if-present

    send:
      needs: 
      - info
      - build
      name: Send Build Bundle to ftp
      runs-on: ubuntu-latest

      steps:    
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "build"
          remoteDir: "${{secrets.subdomainname}}/${{needs.info.outputs.TRANCH_NAME}}"
      
name: React App Staging

on:
  push:
  pull_request:
    branches: [ $default-branch ]

jobs:
  job1:
    runs-on: ubuntu-latest
    id: job_1
    # Map a step output to a job output
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
    - id: step2
      run: echo "::set-output name=test::world"
    outputs:
      output1: ${{ jobs.job_1.steps.step1.outputs.test }}
      output2: ${{ jobs.job_1.steps.step2.outputs.test }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}

    
      env:
        VAR1: ${{ steps.step1.outputs.VAR1 }}