name: 'branch name extractor'
description: 'gets the hypened branch/tag name of the branch/tag that triggered the action'
outputs:
  TRANCH_NAME: 
    description: "Branch or tag name"
    value: ${{steps.step1.outputs.TRANCH_NAME}}
runs:
  using: "composite"
  steps:
  - id: step1
    shell: bash
    run: |
      name=$(echo ${GITHUB_REF////-} | cut --fields="3-" --delimiter='-')
      echo $name
      echo "::set-output name=TRANCH_NAME::$name"